scenarios:
  # long drum synth to drum synth
  - name: synth2synth
    target: training_data/808_long
    output: training_data/funk_long
    tempo: 90

  # short drum synth to drum synth
  - name: synth2synth_s
    target: training_data/808_short
    output: training_data/funk_short
    tempo: 90

  # beatbox to drum kit
  - name: box2kit
    target: training_data/beatbox
    output: training_data/drum_kit
    tempo: 90

models:
  # nested autoencoder
  - name: nested
    type: nested
    args:
      subdiv: 8
      batchsize: 16
      maxepochs: 10000
      lemb: 1
      ladv: 1
      warmup: 2500

  # affine transformation
  - name: affine
    type: affine
    args:
      subdiv: 8
      batchsize: 16
      trials: 100
      samples: 256
      threshold: 100
  
  # match search
  - name: match
    type: match
    args:
      batchsize: 32
      subdiv: 8
      len: 512
  
  # wave2wave projection w/ standard gaussian prior
  - name: w2w_self_mog1
    type: w2w_self
    args:
      epochs: 10000
      batchsize: 32
      lr: 1e-4
      subdiv: 8
      ladv: 1
      warmup: 2500
      mog: 0
  
  # wave2wave transformation w/ standard gaussian prior
  - name: w2w_mog1
    type: w2w
    args:
      epochs: 10000
      batchsize: 32
      lr: 1e-4
      subdiv: 8
      ladv: 1
      warmup: 2500
      mog: 0

   # wave2wave projection w/ mog8 prior
  - name: w2w_self_mog8
    type: w2w_self
    args:
      epochs: 10000
      batchsize: 32
      lr: 1e-4
      subdiv: 8
      ladv: 1
      warmup: 2500
      mog: 8
  
  # wave2wave transformation w/ mog8 prior
  - name: w2w_mog8
    type: w2w
    args:
      epochs: 10000
      batchsize: 32
      lr: 1e-4
      subdiv: 8
      ladv: 1
      warmup: 2500
      mog: 8
